name: Opher CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.0'

    - name: Install dependencies
      run: go mod download

    - name: Build project
      run: go build ./...

    - name: Run tests
      run: go test ./...

    - name: Run static analysis
      run: go vet ./...

    - name: Discord notification (success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "✅ CI Pipeline Passed",
            "embeds":[{
              "title":"Build Information",
              "color":3066993,
              "fields": [
                {"name":"Repository","value":"'"$GITHUB_REPOSITORY"'","inline":true},
                {"name":"Commit","value":"'"$GITHUB_SHA"'","inline":true},
                {"name":"Author","value":"'"$GITHUB_ACTOR"'","inline":true},
                {"name":"Link","value":"'"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'"}
              ],
              "footer": {"text":"Github Actions CI"}
              }]
            }'\
          ${{ secrets.DISCORD_WEBHOOK }}

    - name: Discord notification (failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "❌ CI Pipeline Failed",
            "embeds":[{
              "title":"Build Information",
              "color": 15158332,
              "fields": [
                {"name":"Repository","value":"'"$GITHUB_REPOSITORY"'","inline":true},
                {"name":"Commit","value":"'"$GITHUB_SHA"'","inline":true},
                {"name":"Author","value":"'"$GITHUB_ACTOR"'","inline":true},
                {"name":"Link","value":"'"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'"}
              ],
              "footer": {"text":"Github Actions CI"}
              }]
            }'\
          ${{ secrets.DISCORD_WEBHOOK }}